CC = gcc
CFLAGS = -Wall
LDFLAGS = -lm -lpcap -lpthread

all: scan

scan: senser_main.o senser_networkScan.o
	$(CC) -o $@ $^ $(LDFLAGS)


senser_main.o: senser_main.c senser_networkScan.h
	$(CC) $(CFLAGS) -c $<

senser_networkScan.o: senser_networkScan.c senser_networkScan.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o scan

